import { z } from "zod";

// docs/GROWTH_BOOKING_SHOP_MODULES_CLAUDE.md Sec 4.2: weight/dimensions are
// required per SKU — needed for Bob Go courier rates once Sprint 5 wires
// live shipping, collected now so that migration isn't a second pass over
// every product later.
export const shopProductSchema = z.object({
  title: z.string().trim().min(1, "Enter a product title").max(200),
  sku: z.string().trim().min(1, "Enter a SKU").max(60),
  description: z.string().trim().max(2000).optional().or(z.literal("")),
  basePrice: z.coerce.number().min(0, "Enter a price of 0 or more"),
  weightKg: z.coerce.number().min(0.01, "Enter a weight in kg"),
  lengthCm: z.coerce.number().min(1, "Enter a length in cm"),
  widthCm: z.coerce.number().min(1, "Enter a width in cm"),
  heightCm: z.coerce.number().min(1, "Enter a height in cm"),
  stockQuantity: z.coerce.number().int().min(0).default(0),
});

// Sec 4.2: "Bulk inventory upload... parsed client-side before upload."
// Column headers a client's CSV export is expected to use — kept plain and
// forgiving (case/whitespace normalized before matching) since this is
// filled in by hand in a spreadsheet, not generated by another system.
export const SHOP_CSV_COLUMNS = [
  "title",
  "sku",
  "price",
  "weight_kg",
  "length_cm",
  "width_cm",
  "height_cm",
  "stock_quantity",
  "description",
] as const;

export const shopCsvRowSchema = z.object({
  title: z.string().trim().min(1),
  sku: z.string().trim().min(1),
  price: z.coerce.number().min(0),
  weight_kg: z.coerce.number().min(0.01),
  length_cm: z.coerce.number().min(1),
  width_cm: z.coerce.number().min(1),
  height_cm: z.coerce.number().min(1),
  stock_quantity: z.coerce.number().int().min(0).default(0),
  description: z.string().trim().optional().or(z.literal("")),
});

export const shopCouponSchema = z.object({
  code: z
    .string()
    .trim()
    .min(2, "Enter a code")
    .max(30)
    .transform((v) => v.toUpperCase()),
  discountType: z.enum(["percentage", "fixed_amount"], { message: "Choose a discount type" }),
  discountValue: z.coerce.number().int().min(1, "Enter a discount amount"),
  maxUses: z.coerce.number().int().min(1).optional(),
});

// Sec 4.5: plain text collection address for Sprint 3 — Google Maps
// Places Autocomplete is a flagged, genuinely new paid dependency deferred
// to Sprint 5's decision, not built here.
export const shopCollectionAddressSchema = z.object({
  line1: z.string().trim().min(1, "Enter an address"),
  city: z.string().trim().min(1, "Enter a city"),
  postalCode: z.string().trim().min(1, "Enter a postal code"),
});

// Sec 4: a customer's delivery address at checkout — same shape as
// shop_orders.delivery_address.
export const shopCheckoutSchema = z.object({
  customerName: z.string().trim().min(1, "Enter your name").max(150),
  customerEmail: z.string().email("Enter a valid email"),
  customerPhone: z.string().trim().max(30).optional().or(z.literal("")),
  line1: z.string().trim().min(1, "Enter your delivery address"),
  line2: z.string().trim().max(200).optional().or(z.literal("")),
  suburb: z.string().trim().max(100).optional().or(z.literal("")),
  city: z.string().trim().min(1, "Enter your city"),
  province: z.string().trim().max(100).optional().or(z.literal("")),
  postalCode: z.string().trim().min(1, "Enter your postal code"),
  couponCode: z.string().trim().max(30).optional().or(z.literal("")),
});
